"""
Django settings for tumuratas project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import socket

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g!ya-1-&yx6=ab!_w!h+_7=a-$x%y7krfbkpmogk+eo7kxvo&n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '34.89.211.19',
                 'www.tumuratas-group.de', 'tumuratas-group.de']


# Application definition
INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'captcha',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages',
    'properties',
    'ckeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tumuratas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tumuratas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {

        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'final_db_tumuratas',
        'USER': 'tadmin',
        'PASSWORD': 'Nhdeun277391jshe',
        'HOST': '127.0.0.1',
        'PORT': 5432,
    }
}


"""



'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',



        finale db
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'final_db_tumuratas',
        'USER': 'tadmin',
        'PASSWORD': 'Nhdeun277391jshe',
        'HOST': '127.0.0.1',
        'PORT': 5432,



"""


# EMail stuff
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = socket.gethostbyname('smtp.outlook.com')
#EMAIL_HOST = 'smtp.outlook.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# we will change this email
#EMAIL_HOST_USER = 'tumurataswebsite@gmail.com'
EMAIL_HOST_USER = 'tumurataswebsite@outlook.de'

EMAIL_HOST_PASSWORD = 'Tumwiesb263!'
DEFAULT_FROM_EMAIL = 'tumurataswebsite@outlook.de'
SERVER_EMAIL = 'tumurataswebsite@outlook.de'

#TUMURATAS_EMAIL = 'info@tumuratas-group.de'
TUMURATAS_EMAIL = 'info@tumuratas-group.de'


#EMAIL_PORT = 587
#EMAIL_USE_TLS = True

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# MEDIA

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


# django recaptcha
RECAPTCHA_PUBLIC_KEY = '6Lfz6dkgAAAAAHOpqtdA2_l1CHKDTtBO5q-OPt1i'
RECAPTCHA_PRIVATE_KEY = '6Lfz6dkgAAAAALFwFMyGq1Pxz_cn23LGKb6a9XXr'

RECAPTCHA_REQUIRED_SCORE = 0.86

RECAPTCHA_PROXY = {'http': 'http://127.0.0.1:8000',
                   'https': 'https://127.0.0.1:8000'}
